### PR TITLE
Blizzard changed events id

### PR DESCRIPTION
**Pull request by yefq**
These player unit events id was changed to 272~280 in the new vision.
And added player mouse event.

### CODE REVIEW

**Comment by yefq** [comment]
@Frotty I'm sorry I didn't reply to you in time.
I found that this change led to some errors because the previous mouse event was used as unit event.
I made some modifications and tested them.

Attached is the test code:

```
import ClosureEvents
import HashMap

/*
    format: "EVENT_PLAYER_UNIT_SELL(id = 272) is PlayerUnitEvent."
    0: event name
    1: event id
    2: event type
*/
constant EVENT_PLAYER_UNIT_DEBUG_FORMAT = "{0}(id {1}) is {2}."

constant EVENT_NAME_MAP = new HashMap<int, string>

function eventid.setName(string name)
    EVENT_NAME_MAP.put(this.getHandleId(), name)

function eventid.getName() returns string
    return EVENT_NAME_MAP.get(this.getHandleId())

function eventid.debug()
    let name = this.getName()
    let id   = this.getHandleId().toString()
    string typeName
    if this.isMouseEvent()
        typeName = "MouseEvent"
    else if this.isPlayerunitEvent()
        typeName = "PlayerUnitEvent"
    else
        typeName = "UnknowEvent"
    print(EVENT_PLAYER_UNIT_DEBUG_FORMAT.format(name, id, typeName))


init
    // mouse event (269 to 271)
    EVENT_PLAYER_MOUSE_DOWN.setName("EVENT_PLAYER_MOUSE_DOWN")
    EVENT_PLAYER_MOUSE_MOVE.setName("EVENT_PLAYER_MOUSE_MOVE")
    EVENT_PLAYER_MOUSE_UP.setName("EVENT_PLAYER_MOUSE_UP")
    EVENT_PLAYER_MOUSE_DOWN.debug()
    EVENT_PLAYER_MOUSE_MOVE.debug()
    EVENT_PLAYER_MOUSE_UP.debug()

    // player unit event (272 to 280)
    EVENT_PLAYER_UNIT_SELL.setName("EVENT_PLAYER_UNIT_SELL")
    EVENT_PLAYER_UNIT_CHANGE_OWNER.setName("EVENT_PLAYER_UNIT_CHANGE_OWNER")
    EVENT_PLAYER_UNIT_SELL_ITEM.setName("EVENT_PLAYER_UNIT_SELL_ITEM")
    EVENT_PLAYER_UNIT_SELL.debug()
    EVENT_PLAYER_UNIT_CHANGE_OWNER.debug()
    EVENT_PLAYER_UNIT_SELL_ITEM.debug()

    EVENT_PLAYER_UNIT_SPELL_CHANNEL.setName("EVENT_PLAYER_UNIT_SPELL_CHANNEL")
    EVENT_PLAYER_UNIT_SPELL_CAST.setName("EVENT_PLAYER_UNIT_SPELL_CAST")
    EVENT_PLAYER_UNIT_SPELL_EFFECT.setName("EVENT_PLAYER_UNIT_SPELL_EFFECT")
    EVENT_PLAYER_UNIT_SPELL_CHANNEL.debug()
    EVENT_PLAYER_UNIT_SPELL_CAST.debug()
    EVENT_PLAYER_UNIT_SPELL_EFFECT.debug()

    EVENT_PLAYER_UNIT_SPELL_FINISH.setName("EVENT_PLAYER_UNIT_SPELL_FINISH")
    EVENT_PLAYER_UNIT_SPELL_ENDCAST.setName("EVENT_PLAYER_UNIT_SPELL_ENDCAST")
    EVENT_PLAYER_UNIT_PAWN_ITEM.setName("EVENT_PLAYER_UNIT_PAWN_ITEM")
    EVENT_PLAYER_UNIT_SPELL_FINISH.debug()
    EVENT_PLAYER_UNIT_SPELL_ENDCAST.debug()
    EVENT_PLAYER_UNIT_PAWN_ITEM.debug()

    var _wasDown = false
    EventListener.add(EVENT_PLAYER_MOUSE_DOWN) ->
        if not _wasDown
            print("mouse down")
            _wasDown = true

    var _wasMove = false
    EventListener.add(EVENT_PLAYER_MOUSE_MOVE) ->
        if not _wasMove
            print("mouse move")
            _wasMove = true
        
    var _wasUp = false
    EventListener.add(EVENT_PLAYER_MOUSE_UP) ->
        if not _wasUp
            print("mouse up")
            _wasUp = true
    
    Player(0).setGold(5000)
    Player(0).setLumber(5000)
    Player(0).setState(PLAYER_STATE_RESOURCE_FOOD_CAP, 100)
    // player event 272
    EventListener.add(EVENT_PLAYER_UNIT_SELL) ->
        let u = GetTriggerUnit()
        let t = GetSoldUnit()
        print(u.getName() + " sell " + t.getName())
    // player event 280
    EventListener.add(EVENT_PLAYER_UNIT_PAWN_ITEM) ->
        let u = GetTriggerUnit()
        let t = GetSoldItem()
        print(u.getName() + " pawn " + t.getName())
```

**Comment by Frotty** [comment]
hey, sry for not replying. From what I heard the event-ids got fixed again with 1.30.2
Since the set release date is Dec 1st, I think we might not need this PR after all, or we have to change it back again. 
I will verify it with new patch using ur test and then merge if still needed.
 Thanks 👍

**Comment by yefq** [comment]
I'm glad Blizzard will fix it.
And thank you all for your contribution to Wurst. It's great.

**Comment by Frotty** [comment]
Looks like even more things changed with 1.30.2
Need this for sure now!

**Pull request closed without merging**
