### PR TITLE
Framehandles settings null player

### PR DESCRIPTION
**Pull request by Krypt0n**
@Donach  review?

### CODE REVIEW

**Review by Donach — APPROVED** [review]
All seems ok to me.

**Comment by Frotty** [comment]
Thanks for the PR 👍 
It does indeed look ok, but I'm not a fan of the non-functional dot changes spamming the diff without providing any real benefit.
Rather keep them out or in another, solely format focused PR, since now I don't actually know what the critical change is.

**Comment by Krypt0n** [comment]
Okay Ii can remove that, someone added the dots there in some other commit so I ditched to the same format
Frotty really... "solely format focused PR, since now I don't actually know what the critical change is." such a bullshit comment is really mean. Thought know it better, how disappointing ...

Sometimes you comply about meticulous things like this, then if someone takes an effort for those, you decide randomly to the opposite.

**Comment by Frotty** [comment]
I'm sorry you feel that way, there was no such intent in my message.
I tried phrasing it as neutral as possible and refrain from personal remarks, I would prefer it if you do the same.
Also I didn't say I would not merge the PR - I explained why these changes make reviewing the PR more difficult.
Things exactly like this have caused failing/broken builds after PRs were merged before - formatting changes intermixed with functional changes, resulting in overlooked lines.

**Pull request merged**
