### PR TITLE
A little fix to IDC

### PR DESCRIPTION
**Pull request by Trokkin**
There was a bug with some abilities like thunderbolt or shadowstrike that IDC hasn't casted them. It is fixed by additional setFacing call.

### CODE REVIEW

**Comment by Trokkin** [comment]
Ouch, I didn't see that ton of commits origin/master was behind me somehow, I didn't meant to pull them all o:

**Comment by Frotty** [comment]
Hi, your document changes to Orders screw up the whole alignment again that I manually fixed!
Please move that into different PR or fix the alignment to be nice.

**Comment by Frotty** [comment]
@Trokkin did u test whether d1596a7cc3bdaae221607c58eaa869afcbde5aa2 fixed the import issue?

**Comment by Trokkin** [comment]
@Frotty not yet
Anyway, this PR should be ready to be pulled

**Comment by Frotty** [comment]
Oh hi, kinda forgot about this. I hope the indentation is correct :D will merge.
Thanks a lot! 🌴 👍

**Pull request merged**
