### PR TITLE
Add splice method for linked list

### PR DESCRIPTION
**Pull request by Rhazarian**
Allows to transfer elements from a list in a constant time.

### CODE REVIEW

**Comment by Frotty** [comment]
Cool, could be useful 👍 . But shouldn't the parameter list be destroyed? This is more like a addAll and clear, except not destroying elements.

**Comment by Rhazarian** [comment]
The idea and the name were taken from C++.

https://en.cppreference.com/w/cpp/container/list/splice

Yes, it does the same job as sequenced `addAll` and `clear`, but a lot more faster.

I'm not sure about the destruction of the parameter. On the one hand, it could be useful by allowing you to pass a list returned from another function directly to this one. On the other hand, the parameter list may be wanted to still be used somehow, and implicit destruction may be confusing.

**Comment by Frotty** [comment]
Okay, I guess it's fine then.
Can you add a similar hint then, like in the doc you linked, that this doesn't remove/add elements (relevant for derived lists e.g.) and that the param list will be empty but not destroyed.

**Comment by Rhazarian** [comment]
Extended the hotdoc.

**Comment by Frotty** [comment]
nice, thanks 👍

**Pull request merged**
