### PR TITLE
Wrapers for ability natives / Spaces to tabs

### PR DESCRIPTION
**Pull request by GetLocalPlayer**
Wrapers for Blz[Set/Get]Ability[Tooltip/ExtenedTooltip/Icon/e.t.c.]

### CODE REVIEW

**Comment by GetLocalPlayer** [comment]
Misclick

**Comment by Frotty** [comment]
Thanks, looks good so far except the spaces in front of the opening brackets. Please remove those.

**Comment by GetLocalPlayer** [comment]
whoops

**Comment by GetLocalPlayer** [comment]
Added overload versions for `Set` functions that take `player`.

**Comment by GetLocalPlayer** [comment]
extensions*

**Comment by Frotty** [comment]
Cool thanks 👍

**Pull request merged**
