### PR TITLE
Weather package

### PR DESCRIPTION
**Pull request by GetLocalPlayer**

### CODE REVIEW

**Comment by GetLocalPlayer** [comment]
Instead of WeatherEffect asset

**Comment by Frotty** [comment]
> Instead of WeatherEffect asset

Why? You should add descriptions to your PRs.
In this case I don't see the benefit and it's a breaking change if it were to replace WeatherEffects.

**Comment by GetLocalPlayer** [comment]
Since weathereffect is a handle it requires proper placement. Furthermore that leads us to the necessity of proper function naming to avoid native functions usage that's beyond of the existing package.

**Comment by Frotty** [comment]
The extension functions are fine, the replacement of WeatherEffects not.
You should also add this package as import to the `_Handles` package.

**Comment by GetLocalPlayer** [comment]
Is there any sense to make users import "WeatherEffects"? It'll confuse them.

**Comment by Frotty** [comment]
you can import public the package of course. But we don't want duplicated code nor breaking changes.
Can one make custom weather effects? If not it might be also useful to add additional safety

**Comment by Frotty** [comment]
Sweet 🍭

**Pull request merged**
