### PR TITLE
add root ability when create dummy

### PR DESCRIPTION
**Pull request by yefq**
Make dummy not need to turn when spell or attack.
This will allow dummy to cast spell on countless targets at the same time without missing.

### CODE REVIEW

**Comment by Cokemonkey11** [comment]
LGTM

**Comment by Frotty** [comment]
Yeah, thanks again @yefq 👍 
The only issue is that dummies can't move anymore, but I think that shouldn't be expected in the first place.

**Comment by yefq** [comment]
@Cokemonkey11 @Frotty 
:heart::heart::heart:

**Comment by Frotty** [comment]
Did you see my edits?
Does this cause any issues with attacking?

**Comment by yefq** [comment]
> Did you see my edits?
> Does this cause any issues with attacking?

I ran a simple test, there is no problem.
Attack not need turn, and orb effect is work normal.
(Test with Orb `'Apoi'` and `'ACvs'`)

**Comment by Frotty** [comment]
👍 🍰

**Comment by yefq** [comment]
> 👍 🍰

👍  🍰

**Pull request merged**
