### PR TITLE
Adding FrameHandle wrapperclass

### PR DESCRIPTION
**Pull request by Meisbigmad**
New framehandle natives wrapper class

### CODE REVIEW

**Comment by Frotty** [comment]
Hi, thanks for the contribution 👍 
Looks nice. If you know anything about the new stuff, like framepoints, hot doc would be appreciated.
Make sure to update this PR with changes from ptr, so the CI build will succeed.

**Comment by Frotty** [comment]
Cool, now it builds and we have some doc 👍 
Few things:
- Hotdoc ends with just 1 star `*/`
- Please `/** Inline short comments */`
- Begin sentences with capital letters.

**Comment by Krypt0n** [comment]
Will fix it.

**Comment by Frotty** [comment]
Alright, looking good 👍

**Pull request merged**
