### PR TITLE
Added new extensions for groups.

### PR DESCRIPTION
**Pull request by jonathanmclaus**

### CODE REVIEW

**Comment by jonathanmclaus** [comment]
@Frotty Can you review this?

**Comment by Frotty** [comment]
Did you test this `UnitId2String(id)` ? Does this return the `custom_xxx` name.
Otherwise looks good.

**Comment by jonathanmclaus** [comment]
Yes, it returns the `custom_xxx` format. I've successfully used the functionality in a map, seen [here](https://github.com/island-troll-tribes/island-troll-tribes/pull/367/files#diff-0fc63ebefca077357519772a3cebf701R35).

**Comment by Frotty** [comment]
👍

**Pull request merged**
