### PR TITLE
`.progress()` method for CallbackCounted

### PR DESCRIPTION
**Pull request by GetLocalPlayer**
#396

### CODE REVIEW

**Comment by Frotty** [comment]
Nice 👍  But I think `count` should stay the way it was as to not break anything. Please just make `remaining` save the total call amount and leave other things unchanged.

**Comment by GetLocalPlayer** [comment]
Is it possible, to break anything? `count` is a private field that's not accessable from anywhere except the class it contains as far as I know. Even from children.

**Comment by Frotty** [comment]
Just to be sure and to keep changed to a minimum. There is no benefit of these changes, is there.

**Comment by GetLocalPlayer** [comment]
What about this? I'm placing `count` decreasement before the callback execution, otherwise `.progress()` returns a wrong value (that's > 0) before the callback very first execution.

**Comment by Frotty** [comment]
I don't think that's good, now count values will be different. The original behavior must not be changed by this PR.

**Comment by Frotty** [comment]
It seems fine now, please add some assertions for the callback before the first invocation.

**Comment by GetLocalPlayer** [comment]
> add some assertions for the callback before the first invocation

Like the last two lines of code?

**Comment by Frotty** [comment]
Missed that on phone 👍 
Can you please fix the circleci build?
Check this: https://circleci.com/docs/2.0/oss/#build-pull-requests-from-forked-repositories
Fork builds are enabled on my side, seems like you have to follow the second note:

>Note: If a user submits a pull request to your repository from a fork, but no pipeline is triggered, then the user most likely is following a project fork on their personal account rather than the project itself of CircleCi, causing the jobs to trigger under the user’s personal account and not the organization account. To resolve this issue, have the user unfollow their fork of the project on CircleCI and instead follow the source project. This will trigger their jobs to run under the organization when they submit pull requests.

**Comment by GetLocalPlayer** [comment]
Fixed?

**Comment by Frotty** [comment]
I see, your fork isn't up to date with upstream, consider merging. Looks good now, thanks 👍

**Pull request merged**
