### PR TITLE
Ptr 1.31 frameapi

### PR DESCRIPTION
**Pull request by Krypt0n**
added asset class for framehandelnames; updated framhandle hotdoc

### CODE REVIEW

**Comment by Frotty** [comment]
You are trying to merge into master, I don't think that's correct?

**Comment by Krypt0n** [comment]
Should be change several functions namings? I really don't like `.size` as a setter function

**Comment by Frotty** [comment]
> Should we change several functions namings? I really don't like .size as a setter function

Yea probably since that's in line with data structures.

Looking good 👍

**Comment by Krypt0n** [comment]
Okay will update then, so no need to merge by now :)

**Comment by Krypt0n** [comment]
What do you prefer, something like this:
Getter = framehandle.size()
Setter = framhandle.setSize(real x, real y)
?

**Comment by Frotty** [comment]
I think `.size()` should only be used, if size is readonly, i.e. no setter exists.
If setter and getter exist, you should use setXXX getXXX as usual.

**Comment by Krypt0n** [comment]
Fixed namings, next point will be handling of syncronizing, cause stuff like editbox checkboxes etc. like to desync
so i might work on something with these:'

```
native BlzGetTriggerSyncPrefix                     takes nothing returns string
native BlzGetTriggerSyncData                       takes nothing returns string
native BlzSendSyncData                             takes string prefix, string data returns boolean
native BlzTriggerRegisterPlayerSyncEvent           takes trigger whichTrigger, player whichPlayer, string prefix, boolean fromServer returns event
```

**Comment by Frotty** [comment]
But can merge before that ?

**Comment by Krypt0n** [comment]
yes can be merge, these topics can be added to hotdoc or with some other handles later

**Comment by Frotty** [comment]
Alright, thanks again 👍

**Pull request merged**
