### PR TITLE
Fogmodifier missing functions

### PR DESCRIPTION
**Pull request by GetLocalPlayer**

### CODE REVIEW

**Comment by Frotty** [comment]
nice, but i just noticed that you used spaces instead of tabs in all your contributions, please change to tabs. You can have this done automatically via `.editorconfig`

**Comment by GetLocalPlayer** [comment]
Whitspaces replaced with tabs.

**Comment by Frotty** [comment]
Does a fog modifier need to be stopped before destroying?

**Comment by GetLocalPlayer** [comment]
Nah, it stops by itself.

```
let fog = createVision(Player(0), gg_rct_Test, true)
    ..start()

init
    CreateTrigger()..registerPlayerChatEvent(Player(0), "destroy", true)
    ..addAction() ->
        fog..destr()
```

ezgif-6-3d92d900eb1b

**Pull request merged**
