### PR TITLE
New 1.32.6 natives

### PR DESCRIPTION
**Pull request by GetLocalPlayer**
```

public function framehandle.getChildrenCount() returns int
	return BlzFrameGetChildrenCount(this)

public function framehandle.getChild(int index) returns framehandle
	return BlzFrameGetChild(this, index)

```

### CODE REVIEW

**Comment by Frotty** [comment]
need to update common,j first, so build will succeed.

**Comment by Frotty** [comment]
@GetLocalPlayer will u pr new common.j or at least paste/link?

**Comment by GetLocalPlayer** [comment]
[common.zip](https://github.com/wurstscript/WurstStdlib2/files/4801286/common.zip)

**Comment by Donach** [comment]
Bump - any update on this?

**Comment by Frotty** [comment]
@Donach If u make a PR I will merge it asap

**Comment by Krypt0n** [comment]
https://github.com/wurstscript/WurstStdlib2/pull/358/

**Pull request closed without merging**
