### PR TITLE
Fix for TimedLoop module

### PR DESCRIPTION
**Pull request by WareditorGit**
Fixing a bug introduced by the last commit.

### CODE REVIEW

**Comment by WareditorGit** [comment]
Why this failed :thinking: ?

**Comment by Frotty** [comment]
pls update from master, travis ci sucks with docker apparently :/

**Comment by Frotty** [comment]
> I always do that though ttay24
 I always checkout master from upstream, add my commit and pr

Yea, but I changed the CI settings on master,  so you need to update from master again, and pus hto this PR...

**Comment by Frotty** [comment]
So rn timedloop is totally borked :/ ? I was feeling bad about that last update.
Thanks for catching it ❤️

**Pull request merged**
