### PR TITLE
add dialog handling for closure timers

### PR DESCRIPTION
**Pull request by Cokemonkey11**

### CODE REVIEW

**Comment by Cokemonkey11** [comment]
Click here for changes without whitespace shenanigans: https://github.com/wurstscript/WurstStdlib2/pull/143/files?w=1

**Comment by Frotty** [comment]
How about you remove those whitespace changes, lol.
Stdlib is tabs only.

**Comment by Cokemonkey11** [comment]
The code for doPeriodically seems to be causing a wurst bug. Any idea what's wrong with it?

**Comment by Frotty** [comment]
Because it's more flexible and allows you to do the timer window yourself. But I guess you could merge it with the fully automated approach

**Comment by Cokemonkey11** [comment]
That makes sense, yes. Something like

```
let t = getTimer()
let d = t.addDialog("Hello world", GetLocalPlayer())
t..doAfter(10.) ->
    this.release()
    d.destr()
    print("fuckyeah wurst")
```

Have I got the idea right?

**Comment by theQuazz** [comment]
@Frotty want me to put up a pull request for my extension function?

**Comment by theQuazz** [comment]
@Cokemonkey11 yes that looks right

**Comment by Frotty** [comment]
> want me to put up a pull request for my extension function?

unless coke does it in this one, sure.

**Comment by Cokemonkey11** [comment]
Updated.

**Comment by Frotty** [comment]
- Did you add anything regarding @theQuazz 's suggestion?
- unnecessary whitespace changes still exist
- stuff like `TimerDialogSetTitle` should be replaced by appropriate extension funcs
- not a fan of `tuple dialog_update_fn_res` and `Fn` suffixes as they don't exist in the stdlib for such purposes - in the same package "callback" is used - align for consistency.

**Comment by Frotty** [comment]
@Cokemonkey11 ??
@theQuazz you should make that PR

**Comment by theQuazz** [comment]
@Frotty perhaps we should close in favour of https://github.com/wurstscript/WurstStdlib2/pull/168

**Comment by Frotty** [comment]
i think a nicer api for dialogs as suggested above would still be beneficial.
coke is on vacation so i will wait for his response.

**Comment by Frotty** [comment]
As you're back, @Cokemonkey11 update on this?

**Comment by theQuazz** [comment]
That's a long vacation

**Comment by Cokemonkey11** [comment]
Does #168 actually just close this?

**Comment by Frotty** [comment]
No, but apparently you lack any will to finish this.

**Comment by Cokemonkey11** [comment]
I took a look at latest master branch since #168, and I think this is close enough to https://i.imgur.com/vCrrcHU.jpg that there's no point opening a new PR

**Pull request closed without merging**
